// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6M1kffY8oAOzjSfkjOENEvsUjiXUwPNQ',
    appId: '1:277847069797:web:03a0a9a0e586a94856a28c',
    messagingSenderId: '277847069797',
    projectId: 'todo-list-433fd',
    authDomain: 'todo-list-433fd.firebaseapp.com',
    storageBucket: 'todo-list-433fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUz5FhGghuBSM_vGVsPTVoPnq9RK8Eg0c',
    appId: '1:277847069797:android:d9a0bcfda8ce317656a28c',
    messagingSenderId: '277847069797',
    projectId: 'todo-list-433fd',
    storageBucket: 'todo-list-433fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_NiHe5GdgYo_MBHBTNOfKu4Mqjpy054',
    appId: '1:277847069797:ios:46cf40a3a197199d56a28c',
    messagingSenderId: '277847069797',
    projectId: 'todo-list-433fd',
    storageBucket: 'todo-list-433fd.firebasestorage.app',
    iosBundleId: 'com.domain.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_NiHe5GdgYo_MBHBTNOfKu4Mqjpy054',
    appId: '1:277847069797:ios:46cf40a3a197199d56a28c',
    messagingSenderId: '277847069797',
    projectId: 'todo-list-433fd',
    storageBucket: 'todo-list-433fd.firebasestorage.app',
    iosBundleId: 'com.domain.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6M1kffY8oAOzjSfkjOENEvsUjiXUwPNQ',
    appId: '1:277847069797:web:793380a90329b8e956a28c',
    messagingSenderId: '277847069797',
    projectId: 'todo-list-433fd',
    authDomain: 'todo-list-433fd.firebaseapp.com',
    storageBucket: 'todo-list-433fd.firebasestorage.app',
  );
}
